services:
  backend:
    build:
      context: ./backend/GrafanaBanana.Api
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - grafana-banana-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8080
    networks:
      - grafana-banana-network

networks:
  grafana-banana-network:
    driver: bridge
