server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: grafana-banana-api
    static_configs:
      - targets:
          - localhost
        labels:
          job: grafana-banana-api
          __path__: /var/log/grafana-banana/*.log
          service: grafana-banana-api
          environment: development
