name: CI Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  build-backend:
    name: Build .NET API
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: dotnet restore backend/GrafanaBanana.Api/GrafanaBanana.Api.csproj
    
    - name: Build
      run: dotnet build backend/GrafanaBanana.Api/GrafanaBanana.Api.csproj --no-restore --configuration Release
    
    - name: Test
      run: dotnet test backend/GrafanaBanana.Api/GrafanaBanana.Api.csproj --no-build --configuration Release --verbosity normal

  build-frontend:
    name: Build Angular App
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install dependencies
      run: cd frontend && npm ci
    
    - name: Lint
      run: cd frontend && npm run lint
    
    - name: Build
      run: cd frontend && npm run build
    
    - name: Test
      run: cd frontend && npm run test -- --watch=false --browsers=ChromeHeadless
