name: CI Build

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/pull_request_template.md'
      - 'LICENSE'
  pull_request:
    branches: [ main, develop ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/pull_request_template.md'
      - 'LICENSE'
  workflow_dispatch:

# Cancel in-progress runs for the same branch/PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  build-backend:
    name: Build .NET API
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '9.0.x'
        cache: true
        cache-dependency-path: backend/GrafanaBanana.Api/GrafanaBanana.Api.csproj
    
    - name: Restore dependencies
      run: dotnet restore backend/GrafanaBanana.Api/GrafanaBanana.Api.csproj
    
    - name: Build
      run: dotnet build backend/GrafanaBanana.Api/GrafanaBanana.Api.csproj --no-restore --configuration Release
    
    - name: Test
      run: dotnet test backend/GrafanaBanana.Api/GrafanaBanana.Api.csproj --no-build --configuration Release --verbosity normal

  build-frontend:
    name: Build Angular App
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install dependencies
      run: cd frontend && npm ci --prefer-offline --no-audit
    
    - name: Lint
      run: cd frontend && npm run lint
    
    - name: Build
      run: cd frontend && npm run build -- --configuration production
    
    - name: Test
      run: cd frontend && npm run test -- --watch=false --browsers=ChromeHeadless --code-coverage=false
